name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "altfac" --password-stdin
        docker image build -t altfac/laba5:latest .
        docker push altfac/pyflask:latest
